kind: LocalConfig
apiversion: odo.dev/v1alpha1
ComponentSettings:
  Type: java
  SourceLocation: target/helloopenshift.jar
  SourceType: binary
  Ports:
  - 8080/TCP
  - 8443/TCP
  - 8778/TCP
  Application: app
  Project: my-project
  Name: helloopenshift
  Url:
  - Name: helloopenshift-8080
    Port: 8080
